//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalsViewer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> AnimalTypeId { get; set; }
        public Nullable<int> SkinColorId { get; set; }
        public Nullable<int> LocationId { get; set; }
    
        public virtual AnimalType AnimalType { get; set; }
        public virtual Location Location { get; set; }
        public virtual SkinColor SkinColor { get; set; }
    }
}
